### ISSUE TITLE
web console error

### ISSUE THREAD

**Issue by mystycs** [learn-co-students/has_secure_password_lab-v-000#117]
I am getting this error below when running rspec.

> Web Console is activated in the test environment, which is
> usually a mistake. To ensure it's only activated in development
> mode, move it to the development group of your Gemfile:
> 
> gem 'web-console', group: :development
> 
> If you still want to run it the test environment (and know
> what you are doing), put this in your Rails application
> configuration:
> 
> config.web_console.development_only = false

**Comment by mystycs** [comment]
Also you need to add gem 'bcrypt' to gemfile

**Comment by mendelB** [comment]
@mystycs Thanks for raising this! 
The web console error should now be solved, and I believe adding the `bcrypt` gem is specifically left as an exercise for this lab.

Thanks again!
